export const endpoints = {
  auth: {
    signup: '/auth/signup',
    login: '/auth/login',
    refresh: '/auth/refresh',
    otpRequest: '/auth/otp/request',
    otpVerify: '/auth/otp/verify',
  },
  account: {
    profile: '/account/profile',
    logout: '/account/logout',
    pushTokens: '/account/push-tokens',
    changePassword: '/account/change-password',
  },
  patient: {
    onboarding: '/patient/onboarding',
    profile: '/patient/profile',
    timeline: '/patient/timeline',
    appointments: '/patient/appointments',
    doctors: '/patient/doctors',
    cancelAppointment: (id: string) => `/patient/appointments/${id}/cancel`,
    home: '/patient/home',
    prescriptions: '/patient/prescriptions',
    prescription: (id: string) => `/patient/prescriptions/${id}`,
    invoices: '/patient/invoices',
    invoice: (id: string) => `/patient/invoices/${id}`,
    chat: {
      conversation: '/patient/chat/conversation',
      messages: '/patient/chat/messages',
      read: '/patient/chat/read',
    },
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: '/notifications/mark-all-read',
    delete: (id: string) => `/notifications/${id}`,
  },
  settings: '/settings',
  checkAuth: '/check-auth',
};
