export const routes = {
  home: '/',
  welcome: '/welcome',
  intro: '/intro',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  otpChannelExplainer: '/otp-channel-explainer',
  otpVerification: '/otp-verification',
  onboardingPersonalDetails: '/onboarding-personal-details',
  onboardingMedicalInfo: '/onboarding-medical-info',
  onboardingMedicalHistory: '/onboarding-medical-history',
  onboardingConfirmation: '/onboarding-confirmation',
  onboardingComplete: '/onboarding-complete',
  tabsHome: '/home',
  tabsAppointments: '/appointments',
  tabsPrescriptions: '/prescriptions',
  tabsInvoices: '/invoices',
  notifications: '/notifications',
  medicalTimeline: '/medical-timeline',
  chat: '/chat',
  profile: '/profile',
  editProfile: '/edit-profile',
  changePassword: '/change-password',
  bookAppointment: '/book-appointment',
  prescriptionDetail: (id: string) => `/prescription/${id}` as const,
  invoiceDetail: (id: string) => `/invoice/${id}` as const,
} as const;
