export const routes = {
  home: '/',
  intro: '/intro',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  otpChannelExplainer: '/otp-channel-explainer',
  otpVerification: '/otp-verification',
  onboardingPersonalDetails: '/onboarding-personal-details',
  onboardingMedicalInfo: '/onboarding-medical-info',
  onboardingConfirmation: '/onboarding-confirmation',
  onboardingComplete: '/onboarding-complete',
  tabsHome: '/home',
  tabsAppointments: '/appointments',
  tabsPrescriptions: '/prescriptions',
  tabsInvoices: '/invoices',
  tabsUpdates: '/updates',
  medicalTimeline: '/medical-timeline',
} as const;
