allowBuilds:
  unrs-resolver: true

minimumReleaseAgeExclude:
  - expo-updates@57.0.23

overrides:
  lightningcss: '1.30.1'

patchedDependencies:
  react-native-css@3.0.7: patches/react-native-css@3.0.7.patch
